# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodle-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter instantnoodle instantnoodlep kebab,$(TARGET_DEVICE)),)

endif
